/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_highperformancespark_examples_ffi_SumJNI */

#ifndef _Included_com_highperformancespark_examples_ffi_SumJNI
#define _Included_com_highperformancespark_examples_ffi_SumJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_highperformancespark_examples_ffi_SumJNI
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_highperformancespark_examples_ffi_SumJNI_sum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
